"""add_dep_complaint_severe_count

Revision ID: 20446a1cceb7
Revises: l5m8n1o4p7q0
Create Date: 2026-04-12 11:37:47.667221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20446a1cceb7'
down_revision: Union[str, Sequence[str], None] = 'l5m8n1o4p7q0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_signals')
    op.add_column('realtime_modifiers', sa.Column('dep_complaint_count', sa.Integer(), nullable=True))
    op.add_column('realtime_modifiers', sa.Column('dep_severe_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('realtime_modifiers', 'dep_severe_count')
    op.drop_column('realtime_modifiers', 'dep_complaint_count')
    op.create_table('user_signals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('venue_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('noise_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('headcount_est', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('user_signals_venue_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_signals_pkey'))
    )
    # ### end Alembic commands ###
