from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '28c0bc5b81da'
down_revision: Union[str, Sequence[str], None] = '6ea91e0077e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('realtime_modifiers', sa.Column('tomtom_traffic_congestion', sa.Float(), nullable=True))
    op.add_column('realtime_modifiers', sa.Column('tomtom_incidents_nearby', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('realtime_modifiers', 'tomtom_incidents_nearby')
    op.drop_column('realtime_modifiers', 'tomtom_traffic_congestion')
    # ### end Alembic commands ###
