"""add_photos_to_venues

Revision ID: 911a9da8d14b
Revises: j3k6l9m2n5o8
Create Date: 2026-04-11 09:19:03.622094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '911a9da8d14b'
down_revision: Union[str, Sequence[str], None] = 'j3k6l9m2n5o8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('photos', sa.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'photos')
    # ### end Alembic commands ###
