"""add_realtime_modifier_venue_timestamp_index

Revision ID: 96c868bebf02
Revises: 911a9da8d14b
Create Date: 2026-04-11 09:51:05.126030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96c868bebf02'
down_revision: Union[str, Sequence[str], None] = '911a9da8d14b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_rt_mod_venue_timestamp', 'realtime_modifiers', ['venue_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_rt_mod_venue_timestamp', table_name='realtime_modifiers')
    # ### end Alembic commands ###
